### ISSUE TITLE
S3X ACLs are broken

### ISSUE THREAD

**Issue by dyusupov** [Nexenta/edgefs#206]
### Summary 

S3X ACLs are broken, perhaps during the transition from 2.x

### Steps to reproduce the behavior

set X-ACL-On to true, restart service

### Expected behavior

Should not crash and should work

### Actual behavior

s3-proxy fails with:

/opt/nedge/restapi/s3/service_ctrl.js:83
                auth.access({
                ^
ReferenceError: auth is not defined
    at /opt/nedge/restapi/s3/service_ctrl.js:83:17
    at iterate (/opt/nedge/restapi/node_modules/async/lib/async.js:256:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/opt/nedge/restapi/node_modules/async/lib/async.js:275:9)
    at /opt/nedge/restapi/s3/service_ctrl.js:79:19
    at /opt/nedge/restapi/drivers/ccow/blob_ccow.js:2150:21
    at /opt/nedge/restapi/node_modules/async/lib/async.js:49:16
    at /opt/nedge/restapi/node_modules/async/lib/async.js:354:13
    at /opt/nedge/restapi/node_modules/async/lib/async.js:49:16
    at replenish (/opt/nedge/restapi/node_modules/async/lib/async.js:308:29)
    at /opt/nedge/restapi/node_modules/async/lib/async.js:320:29

### EdgeFS version

1.1.18

### Deployment type

- [x] Kubernetes with Rook Operator
- [ ] Docker Compose

- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [x] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

- [x] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [ ] Ubuntu 18.04.x
- [ ] Other

**Comment by dyusupov** [comment]
Fixed in latest.
