### ISSUE TITLE
S3 downloads fail on k3d provisioned k3s cluster

### ISSUE THREAD

**Issue by ibloat** [Nexenta/edgefs#552]
### Summary 
Downloading files with the minio CLI via the S3 interface fails on a newly provisioned k3d cluster following the instructions from https://rook.io/docs/rook/v1.3/edgefs-s3-crd.html

### Steps to reproduce the behavior
```
cd rook-release-1.3/cluster/examples/kubernetes/edgefs
kubectl create -f operator.yaml
kubectl create -f cluster.yaml

kubectl exec -it -n rook-edgefs rook-edgefs-mgr-xxxxxxxxxx-xxxxx -- env COLUMNS=$COLUMNS LINES=$LINES TERM=linux toolbox

efscli system init
efscli cluster create Cluster
efscli tenant create Cluster/Tenant
efscli bucket create Cluster/Tenant/bucket
efscli service create s3 s3-cluster
efscli service serve s3-cluster Cluster/Tenant
efscli service config s3-cluster X-Domain service.local

ctrl-D

kubectl create -f s3.yaml
```

```yaml
#Cluster spec, other files are unaltered
spec:
  edgefsImageName: edgefs/edgefs:1.3.29
  serviceAccount: rook-edgefs-cluster
  dataDirHostPath: /var/lib/edgefs
  resourceProfile: embedded
  sysRepCount: 3
  storage:
    useAllNodes: true
    directories:
    - path: /media
```

```bash
kubectl port-forward -n rook-edgefs rook-edgefs-s3-s3-cluster-xxxxxxxxxx-xxxxx 9982

mc config host add k3d-rook http://localhost:9982 # ok
mc cp some.iso k3d-rook/bucket/some.iso  # succeeds
mc cat k3d-rook/bucket/some.iso | md5sum # fails
mc cp k3d-rook/bucket/some.iso /tmp/xxx # fails
```

### Expected behavior

Reading uploaded files works

### Actual behavior

Download fails

### EdgeFS version

1.3.29

### Deployment type

- [x] Kubernetes with Rook Operator
- [ ] Docker Compose

- [x] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [x] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

```bash
k3d c -n rook --image docker.io/rancher/k3s:v1.17.4-k3s1 -w 2
export KUBECONFIG="$(k3d get-kubeconfig --name='rook')"
```

- [ ] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [ ] Ubuntu 18.04.x
- [x] Other (MacOS Docker)

### Logs

Error thrown in `rook-edgefs-s3-s3-cluster-xxxxxxxxxx-xxxxx` on read operations:
```
Tue, 28 Apr 2020 08:18:45 GMT info s3 (insecure) is listening on 9982 timeout: 600s
Tue, 28 Apr 2020 08:18:45 GMT info s3 (secure) is listening on 9443 timeout: 600s

/opt/nedge/restapi/s3/object_ctrl.js:206
    var response = (new Stream()).Writable();
                                  ^
TypeError: Object #<Stream> has no method 'Writable'
    at loadParts (/opt/nedge/restapi/s3/object_ctrl.js:206:35)
    at Object.callback (/opt/nedge/restapi/s3/object_ctrl.js:507:17)
    at /opt/nedge/restapi/node_modules/async/lib/async.js:853:35
    at _arrayEach (/opt/nedge/restapi/node_modules/async/lib/async.js:81:9)
    at /opt/nedge/restapi/node_modules/async/lib/async.js:852:17
    at /opt/nedge/restapi/node_modules/async/lib/async.js:40:16
    at /opt/nedge/restapi/drivers/ccow/blob_ccow.js:729:40
```

**Comment by dyusupov** [comment]
It could be memory related issue. Could you please try to comment out embedded profile?

**Comment by ibloat** [comment]
Until now I only uploaded files of ~700MiB and am encountering the same issue without the embedded profile.
Same with ~300MiB files.

Small files (tried <10MiB) it turns out work fine though so your suggestion seems to be on point.

```
Starting s3 in foreground.
Wed, 29 Apr 2020 05:30:20 GMT info s3 totalmem: 9969M, freemem: 508M
Wed, 29 Apr 2020 05:30:20 GMT info s3 memory: {"limit":381,"memPerWorker":4096}
Wed, 29 Apr 2020 05:30:20 GMT info s3 number of workers: 1
```
